services:
  faker:
    image: jupegarnica/faker.deno.dev
    ports:
      - 80:8000
    networks:
      - fetch-net
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "81:80"
    networks:
      - fetch-net

  test:
    networks:
      - fetch-net
    image: denoland/deno
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - HOST=http://faker:80
    # command: deno task test
    command: deno task test-watch
    depends_on:
      - faker

networks:
  fetch-net:
    driver: bridge