---
host: <%= Deno.env.get('HOST') || 'https://faker.deno.dev' %>

---

###
---
id: run command with request
command: echo "with request" && sleep 2 && echo "2s"
---
GET /?delay=1000
x-quiet: true

###

---
id: run command without request
command: echo "without request"
---
###
---
id: fail command
command: echo "fail command" && exit 133
---
###

---
id: log to stderr
command: sh toStderr.sh
ignore: true
---

###
---
id: run command without stdout
timeout: 2000
command: sleep 5
ignore: true
---