

###
---
redirect: follow
needs: assert json body
---
GET https://faker.deno.dev/image/avatar
quiet: true

###
---
id: assert json body
---
GET https://httpbin.org/json

HTTP/1.1 200 OK
Content-Type: application/json

{
  "slideshow": {
    "title": "Sample Slide Show"
  },
  "unexpected": "this should not be here"
}
