---
host: <%= Deno.env.get('HOST') || 'https://faker.deno.dev' %>
---

###
---
id: json
---
POST /pong?quiet=true
content-type: application/json

{
    "name": "pong asd"
}

HTTP/1.1 200 OK


###
---
id: xml
---
POST /pong
log-level: critical
host: faker.deno.dev
content-type: application/xml

<xml>
    <name>pong asd</name>
    <verbose>true</verbose>
</xml>

HTTP/1.1 201 OK



###
---
id: yaml
---

POST /pong
x-quiet: true
Content-Type: application/x-yaml

id: pong asd
list:
    - 1
    - 2
    - 3
obj: {a: 1, b: 2}



HTTP/1.1 200 OK


###
---
redirect: manual
id: redirect
---
GET /image/avatar
log-level: critical
