---
host: <%= Deno.env.get("HOST") || "https://faker.deno.dev" %>
<% globalThis.a = 2; %>
<% let a = 1; %>
---

###
---
id: dos
---
POST /?body=<%= globalThis.a %>
quiet: true

HTTP/1.1 200

2
###


POST /?body=2
quiet: true

HTTP/1.1 200

<%= dos.body %>
