---
host: <%= Deno.env.get('HOST') || 'https://faker.deno.dev' %>
# import: ../http/failFast.http
---

###
---
import: ./pass.http
id: needPass.http
---
GET /pong?body=<%= passId.body %>
quiet: true

HTTP/1.1 200 OK

passed