---
host: <%= Deno.env.get('HOST') || 'https://faker.deno.dev' %>
---
###
---
id: needs401
needs: 401
---
POST /pong?status=202
quiet: true

hola

HTTP/1.1 202 Accepted

<%= body %>

###
---
id: 401
---

POST /pong?status=401
quiet: true

HTTP/1.1 401 Unauthorized

###
---
id: 400
---

GET /pong?status=400
quiet: true

HTTP/1.1 400 Bad Request