---
host: <%= Deno.env.get('HOST') || 'https://faker.deno.dev' %>
---
###

---
id:  block1
needs: block2
---
POST /pong
x-quiet: true

<%= block2.meta.id + '?' %>

###
---
id:  block2
needs: block1
description: must not enter on infinite loop
---
POST /pong
x-quiet: true

<%= block1.meta.id + '??' %>
