---
host: <%= Deno.env.get('HOST') || 'https://faker.deno.dev' %>
---
###

---
id:  block_1
needs: block_2
---
POST /pong
x-quiet: true

<%= block_2.meta.id + '?' %>

###
# description: must not enter on infinite loop
---
id:  block_2
needs: block_1

---
POST /pong
x-quiet: true
x-body-block1: <%= block_1.body || 'not found' %>

<%= block_1.meta.id + '??' %>


###
# description: must run latest
---
id:  block_3
needs: block_1
---
POST /pong
x-quiet: true

<%= block_1.meta.id + '??' %>
