---
host: <%= Deno.env.get("HOST") || "https://faker.deno.dev "%>
---
###
---
id: no ignored
---
GET /pong?status=204
quiet: true

HTTP/1.1 204 No Content

###
---
id: ignored
only: <%= !!Deno.env.get('TEST_ONLY') %>
---

GET /pong?status=203
quiet: true

HTTP/1.1 203 Non Authoritative Information
###