---
host: <%= Deno.env.get("HOST") || "https://faker.deno.dev "%>
---
###
---
name: 204 No Content
---
GET /pong?status=204
quiet: true

HTTP/1.1 204 No Content

###
---
only: true
name: 203 Non-Authoritative Information
---

GET /pong?status=203
quiet: true

HTTP/1.1 203 Non Authoritative Information
###