---
host: <%= Deno.env.get('HOST') || 'https://faker.deno.dev' %>
---

###
---
id: response conditional
---
GET  /pong?body=1


HTTP/1.1 200 OK

<% if (Math.random() > 0.5) { %>
1
<% } else { %>
2
<% } %>

###

---
id: request conditional
---

<% if (Math.random() > 0.5) { %>
GET /pong?body=2
<% } else { %>
GET /pong?body=3
<% } %>

HTTP/1.1 200 OK


###

---
id: meta conditional
<% if (Math.random() > 0.5) { %>
rnd: 1
<% } else { %>
rnd: 2
<% } %>
---

GET /pong?body=4


HTTP/1.1 200 OK
