---
delta: 1000
host: <%= process.env['HOST'] || 'https://faker.deno.dev/pong' %>
---

###
---
id: first
---
GET ?delay=<%=meta.delta%>

###
---
id: second
---
GET ?delay=<%=meta.delta%>

###

---
id: third
---
GET ?delay=<%=meta.delta%>

###
---
id: skipped
ignore: true
---
GET ?delay=<%=meta.delta%>

###
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>

GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>

GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>

GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
GET ?delay=<%=meta.delta%>
