---
host: <%= Deno.env.get('HOST') || 'https://faker.deno.dev' %>
---
###
---
timeout: 50
---
GET /pong?delay=100
x-quiet: true

HTTP/1.1 200 OK

###
---
id: force no timeout
timeout: 0
---
GET /pong?delay=50
x-quiet: true


###
---
id: delay
delay: 10
---
GET /pong?delay=200
x-quiet: true


###
---
id: delay + timeout
delay: 100
timeout: 1000
---
GET /pong?delay=1
x-quiet: true

HTTP/1.1 200 OK
