---
host: <%= Deno.env.get('HOST') || 'https://faker.deno.dev' %>
---
###
---
timeout: 100
---
GET /pong?delay=200
x-quiet: true

HTTP/1.1 200 OK

###
---
id: force no timeout
timeout: 0
---
GET /pong?delay=200
x-quiet: true


###
---
id: delay
delay: 10
---
GET /pong?delay=200
x-quiet: true


###
---
id: delay + timeout
delay: 200
timeout: 400
---
GET /pong?delay=200
x-quiet: true

HTTP/1.1 200 OK
