## create readme on changes to src/cli.ts
name: readme
on:
  workflow_dispatch:
  push:
    paths:
      - src/help.ts
jobs:

  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - run: deno task readme
      - uses: EndBug/add-and-commit@v9
        with:
          message: "docs: update readme"
          add: "README.md"
