## create readme on changes to src/cli.ts
name: test and publish
on:
  workflow_dispatch:

  push:
    tags:
      - 'v*'
    paths:
      - src/**
      - mod.ts

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci
      - run: npm test

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to JSR
        if: startsWith(github.ref, 'refs/tags/v')
        run: npx jsr publish
